### ISSUE TITLE
Services tab

### ISSUE THREAD

**Issue by konektid** [SeanPlusPlus/konektid#3]
- change font of this text to match the grey text formatting under my picture:
  Konektid designs and implements international business strategy for emerging markets. The scope of our work ranges from introductions to local stakeholders, to launching full-scale operations in a new market. Konektid is experienced in identifying how to capitalize on international business opportunities, while mitigating risks.
- There are 5 services. Change the formatting from three to five services so the layout looks like this:
  "Local Insight" below image                        Description text            Konektid's experience
  "Stakeholder Mapping" below image          Description text            Konektid's experience
  "Strategic Immersion" below image            Description text            Konektid's experience
  "Partnerships" below image                        Description text            Konektid's experience
  "Strategy Implementation" below image     Description text            Konektid's experience
- "Partnerships" and "Strategy Implementation" will need images. For "Partnerships" use shaking hands. For "Strategy Implementation" use gears turn image.
- For each of five "Konektid's experience" format thus:
  Konektid's experience:
  Client profile: text....
  Challenge: text.....
  Result: text......
- For content, use content currently on site for first three services (Local Insight; Stakeholder mapping; Strategic Immersion). For remaining two services use this content:

Partnerships

Governments and international banks invest $150 billion annually in development projects in emerging markets. Konektid’s team has decades of experience designing and managing these projects and we use this knowledge to help our clients access these resources through partnerships. These partnerships allow our clients to capitalize on opportunities in emerging markets and mitigate market entry risks through leveraged financing, deeper integration into the local market, and improved local branding.

Konektid's experience:
Client profile: Fortune 500 Healthcare Company
Challenge: Access new medical device innovations in emerging markets that are target to local needs and are ready to be brought to market.
Result: Konektid brokered a partnership between our client and a government-funded organization investing more than $20 million of non-dilutive capital annually in new medical innovations in emerging markets. The partnerships allowed our client to connect to successful recipients of this investment to identify the highest-potential business opportunities for our client to scale up commercially. In addition, Konektid secured a commitment of up to $1 million of additional leveraged financing to bring these innovations to market.

Strategy Implementation

Konektid accelerates business growth in emerging markets by designing and implementing business models that meet identified local needs. These include strategies for increasing available financing for customers, development of a local distribution network, and securing access to key agricultural products and manufacturing supplies. Konektid supports the launch of these business models through locally-targeted marketing initiatives.

Konektid's experience:
Client profile: Fortune 500 Healthcare Company
Challenge: Increase access to financing for local customers to purchase our client’s products and services. 
Result: Konektid structured a framework to create a revolving credit fund that leverages our client’s investment by a magnitude of 20, creating millions of dollars in available credit for purchase of our client’s products in the target market. The framework included identifying and vetting a local lending partner, structuring a revolving fund of credit, and providing guarantee against loan defaults.

**Comment by SeanPlusPlus** [comment]
there are too many items in this ... break it out more please

**Comment by SeanPlusPlus** [comment]
actually ... nevermind ... i understand this

**Comment by SeanPlusPlus** [comment]
also, use this icon set for choosing new icons:

http://fortawesome.github.io/Font-Awesome/icons/

**Comment by SeanPlusPlus** [comment]
updated. okay to close?
