### ISSUE TITLE
About tab

### ISSUE THREAD

**Issue by konektid** [SeanPlusPlus/konektid#5]
Change formatting and font of "Our Story" and "About Konektid" sections to match formatting and font of grey CEO description under my picture, including centering and bolding text "Our Story" and "About Konektid".
- Make new section for paragraph just above country list (formatting and font of this section should match "Our Story" and "About Konektid". Section should be titled "High Opportunity Markets". Content under should read:
  Konektid’s work is focused on high opportunity international markets, sometimes known as emerging markets, where there is a combination of rapid economic growth and significant international development investment. These high opportunity international markets include:
- List is great, just please bold the region for each bullet point. These regions are Africa; Asia; Eurasia; Latin America; Middle East
- Our Name sub-section. Keep content the same, but have formatting and font match grey CEO description under my picture.

**Comment by SeanPlusPlus** [comment]
updated. okay to close?
