### ISSUE TITLE
Our Blog tab

### ISSUE THREAD

**Issue by konektid** [SeanPlusPlus/konektid#7]
Leave as is for now, but soon we'll have the first blog post up there and I'd like to see a way for those blog posts to appear on konektid.com in some way. No need for action on this now, we'll cross this bridge once that post is written.

For now only action item is to add "Blog" as a tab to the header menu between "Team" and "Contact"

**Comment by SeanPlusPlus** [comment]
i do not like this idea.

top level navigation should not point away from a web site.
