### ISSUE TITLE
Contact tab

### ISSUE THREAD

**Issue by konektid** [SeanPlusPlus/konektid#8]
Small changes down for bottom of page:
- change "Contact Us" above email address to "Ready to go global?" 
- Directly below "Ready to go global?" add "Email us at:"
- Email address should be below "Email us at:"
- change email address from mike@konketid.com to connect@konektid.com
- Change copyright year to 2015
- Change "percentage of profits donated to cancer research" to "Portion of profits donated to lung cancer research."
- Have this link open a new tab, rather than take visitor away from konektid.com
- Feel free to a note at the bottom, something like "Site designed by SeanPlusPlus" and like to your website or twitter or wherever.

**Comment by SeanPlusPlus** [comment]
done. okay to close?
