### ISSUE TITLE
Services tab

### ISSUE THREAD

**Issue by konektid** [SeanPlusPlus/konektid#9]
In each of the five services there is a "Konektid's experience" section under it. Can you have "Client Profile", "Challenge", and "Result" each start on a new line?

So:

Text....

Konektid's experience:
Client profile: ......
Challenge: ......
Result: .......

Also, for the first service - Local Insight - under "Konektid's experience" please delete word "Business" from phrase "Business Challenge."

Thanks!

**Comment by SeanPlusPlus** [comment]
done.

https://github.com/SeanPlusPlus/konektid/commit/d6256f2ff6ad67153e31217959faef6e408ea5d2
